S = [];
S.A = [0;
];
S.Bu = [b(3), a(1);
];
S.Baux = [;
];
S.Baff = [0;
];
S.C = [0;
0;
0;
];
S.Du = [0, 0;
0, 0;
0, 0;
];
S.Daux = [;
;
;
];
S.Daff = [a(2);
c(2);
a(1)*b(1)*c(1)+a(1)*b(2)*c(3)+a(1)*b(3)*c(5)+a(2)*b(1)*c(2)+a(2)*b(2)*c(4)+a(2)*b(3)*c(6);
];
S.Ex = [-1;
1;
0;
0;
0;
0;
];
S.Eu = [0, 0;
0, 0;
-1, 0;
0, -1;
1, 0;
0, 1;
];
S.Eaux = [;
;
;
;
;
;
];
S.Eaff = [10000;
10000;
10000;
10000;
10000;
10000;
];
S.nu = 2;
S.nx = 1;
S.ny = 3;
S.nw = 0;
S.InputName = {'U'};
S.InputKind = {'r'};
S.InputLength = {2};
S.StateName = {'X'};
S.StateKind = {'r'};
S.StateLength = {1};
S.OutputName = {'Y', 'Y2'};
S.OutputKind = {'r', 'r'};
S.OutputLength = {2, 1};
S.AuxName = {};
S.AuxKind = {};
S.AuxLength = {};
S.ParameterName = {'a', 'b', 'c'};
S.ParameterKind = {};
S.ParameterLength = {2, 3, 6};
S.xl = -10000;
S.xu = 10000;
S.ul = [-10000;-10000];
S.uu = [10000;10000];
S.yl = [-10000;-10000;-10000];
S.yu = [10000;10000;10000];
S.wl = zeros(0,1);
S.wu = zeros(0,1);
S.j.xr = 1;
S.j.xb = [];
S.j.ur = [1;2];
S.j.ub = [];
S.j.yr = [1;2;3];
S.j.yb = [];
S.j.d = [];
S.j.z = [];
S.j.w_auto_bin = zeros(0,1);
S.j.eq = zeros(1,0);
S.j.ineq = [1 2 3 4 5 6];
S.J.X = 'r';
S.J.U = 'rr';
S.J.Y = 'rrr';
S.J.W = [];
S.nxb = 0;
S.nxr = 1;
S.nub = 0;
S.nur = 2;
S.nyb = 0;
S.nyr = 3;
S.nd = 0;
S.nz = 0;
S.nc = 6;
S.symtable = {struct('name', 'a', 'orig_type', 'parameter', 'type', 'parameter', 'kind', 'real'), struct('name', 'b', 'orig_type', 'parameter', 'type', 'parameter', 'kind', 'real'), struct('name', 'c', 'orig_type', 'parameter', 'type', 'parameter', 'kind', 'real'), struct('name', 'X', 'orig_type', 'state', 'type', 'state', 'kind', 'real'), struct('name', 'U', 'orig_type', 'input', 'type', 'input', 'kind', 'real'), struct('name', 'Y', 'orig_type', 'output', 'type', 'output', 'kind', 'real'), struct('name', 'Y2', 'orig_type', 'output', 'type', 'output', 'kind', 'real')};
S.MLDisvalid = 1;
S.connections.variables = [];
S.connections.table = [];
S.name = 'test030';
