S = [];
S.A = [0, 0;
0, 0;
];
S.Bu = [0;
0;
];
S.Baux = [;
;
];
S.Baff = [c;
77;
];
S.C = [0, 0;
];
S.Du = [1;
];
S.Daux = [;
];
S.Daff = [0;
];
S.Ex = [-1, 0;
0, -1;
1, 0;
0, 1;
0, 0;
0, 0;
];
S.Eu = [0;
0;
0;
0;
-1;
1;
];
S.Eaux = [;
;
;
;
;
;
];
S.Eaff = [10000;
10000;
10000;
10000;
10000;
10000;
];
S.nu = 1;
S.nx = 2;
S.ny = 1;
S.nw = 0;
S.InputName = {'U'};
S.InputKind = {'r'};
S.InputLength = {1};
S.StateName = {'X'};
S.StateKind = {'r'};
S.StateLength = {2};
S.OutputName = {'Y'};
S.OutputKind = {'r'};
S.OutputLength = {1};
S.AuxName = {};
S.AuxKind = {};
S.AuxLength = {};
S.ParameterName = {'c'};
S.ParameterKind = {};
S.ParameterLength = {1};
S.xl = [-10000;-10000];
S.xu = [10000;10000];
S.ul = -10000;
S.uu = 10000;
S.yl = -10000;
S.yu = 10000;
S.wl = zeros(0,1);
S.wu = zeros(0,1);
S.j.xr = [1;2];
S.j.xb = [];
S.j.ur = 1;
S.j.ub = [];
S.j.yr = 1;
S.j.yb = [];
S.j.d = [];
S.j.z = [];
S.j.w_auto_bin = [];
S.j.eq = zeros(1,0);
S.j.ineq = [1 2 3 4 5 6];
S.J.X = 'rr';
S.J.U = 'r';
S.J.Y = 'r';
S.J.W = [];
S.nxb = 0;
S.nxr = 2;
S.nub = 0;
S.nur = 1;
S.nyb = 0;
S.nyr = 1;
S.nd = 0;
S.nz = 0;
S.nc = 6;
S.symtable = {struct('name', 'nu', 'orig_type', 'parameter', 'type', 'parameter', 'kind', 'real'), struct('name', 'c', 'orig_type', 'parameter', 'type', 'parameter', 'kind', 'real'), struct('name', 'X', 'orig_type', 'state', 'type', 'state', 'kind', 'real'), struct('name', 'U', 'orig_type', 'input', 'type', 'input', 'kind', 'real'), struct('name', 'Y', 'orig_type', 'output', 'type', 'output', 'kind', 'real')};
S.MLDisvalid = 1;
S.connections.variables = [];
S.connections.table = [];
S.name = 'test040c';
