S = [];
S.A = [0;
];
S.Bu = [1, 0;
];
S.Baux = [1;
];
S.Baff = [sin(x)+exp(A*h3_power_internal(B, -1));
];
S.C = [1;
];
S.Du = [0, 0;
];
S.Daux = [0;
];
S.Daff = [0;
];
S.Ex = [-1;
1;
0;
0;
0;
0;
0;
0;
0;
];
S.Eu = [0, 0;
0, 0;
-1, 0;
1, 0;
0, -1;
0, 1;
0, 0;
0, 0;
0, -1;
];
S.Eaux = [0;
0;
0;
0;
0;
0;
-1;
1;
1;
];
S.Eaff = [10000;
10000;
10000;
10000;
10000;
10000;
10000;
10000;
0;
];
S.nu = 2;
S.nx = 1;
S.ny = 1;
S.nw = 1;
S.InputName = {'u1', 'u2'};
S.InputKind = {'r', 'r'};
S.InputLength = {1, 1};
S.StateName = {'x'};
S.StateKind = {'r'};
S.StateLength = {1};
S.OutputName = {'y'};
S.OutputKind = {'r'};
S.OutputLength = {1};
S.AuxName = {'a'};
S.AuxKind = {'r'};
S.AuxLength = {1};
S.ParameterName = {'A', 'B'};
S.ParameterKind = {};
S.ParameterLength = {1, 1};
S.xl = -10000;
S.xu = 10000;
S.ul = [-10000;-10000];
S.uu = [10000;10000];
S.yl = -10000;
S.yu = 10000;
S.wl = -10000;
S.wu = 10000;
S.j.xr = 1;
S.j.xb = [];
S.j.ur = [1;2];
S.j.ub = [];
S.j.yr = 1;
S.j.yb = [];
S.j.d = [];
S.j.z = 1;
S.j.w_auto_bin = [];
S.j.eq = 9;
S.j.ineq = [1 2 3 4 5 6 7 8];
S.J.X = 'r';
S.J.U = 'rr';
S.J.Y = 'r';
S.J.W = 'r';
S.nxb = 0;
S.nxr = 1;
S.nub = 0;
S.nur = 2;
S.nyb = 0;
S.nyr = 1;
S.nd = 0;
S.nz = 1;
S.nc = 9;
S.symtable = {struct('name', 'A', 'orig_type', 'parameter', 'type', 'parameter', 'kind', 'real'), struct('name', 'B', 'orig_type', 'parameter', 'type', 'parameter', 'kind', 'real'), struct('name', 'x', 'orig_type', 'state', 'type', 'state', 'kind', 'real'), struct('name', 'u1', 'orig_type', 'input', 'type', 'input', 'kind', 'real'), struct('name', 'u2', 'orig_type', 'input', 'type', 'input', 'kind', 'real'), struct('name', 'y', 'orig_type', 'output', 'type', 'output', 'kind', 'real'), struct('name', 'a', 'orig_type', 'aux', 'type', 'aux', 'kind', 'real')};
S.MLDisvalid = 1;
S.connections.variables = [];
S.connections.table = [];
S.name = 't1';
